name: ats641_2022
channels:
   - conda-forge
dependencies:
   - python=3.8
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - siphon
   - pandas
   - pip
   - xarray
   - ipywidgets
   - ffmpeg
   - boto3
   - botocore
   - jupyterlab
   - netcdf4
   - cfgrib
   - plotly
   - pip:
      - python-awips
